kind: ConfigMap
apiVersion: v1
metadata:
  name: basket-cm
  namespace: {{ .Values.namespace }}
  labels:
    app: eshop
    service: basket
data:
  ASPNETCORE_ENVIRONMENT: Development
  ASPNETCORE_URLS: http://0.0.0.0:80
  IdentityUrl: http://identity-api
  IdentityUrlExternal: http://{{ .Values.hostName }}/identity
  SeqServerUrl: http://seq

---

kind: Deployment
apiVersion: apps/v1
metadata:
  name: basket
  namespace: {{ .Values.namespace }}
  labels:
    app: eshop
    service: basket
spec:
  replicas: 1
  selector:
    matchLabels:
      service: basket
  template:
    metadata:
      labels:
        app: eshop
        service: basket
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9090"
        prometheus.io/path: "/"        
    spec:
      containers:
        - name: basket-api
          image: eshopdapr/basket.api:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: api-http
              containerPort: 80
              protocol: TCP
          envFrom:
            - configMapRef:
                name: basket-cm
          readinessProbe:
            httpGet:
              path: /hc
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5

---

apiVersion: v1
kind: Service
metadata:
  name: basket-api
  namespace: {{ .Values.namespace }}
  labels:
    app: eshop
    service: basket
spec:
  ports:
    - name: http
      port: 80
      targetPort: api-http
  selector:
    service: basket
