{{- if .Values.DEPLOY.SQL -}}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: eshop-sql-secrets
  namespace: {{ .Values.NAMESPACE }}
spec:
  provider: azure
  secretObjects:
  - secretName: eshop-sql-secrets                   
    type: Opaque                            
    data: 
    - key: catalogdb-connection-string
      objectName: catalogdb-connection-string                            
    - key: identitydb-connection-string
      objectName: identitydb-connection-string
    - key: orderingdb-connection-string
      objectName: orderingdb-connection-string    
    - key: webhooksdb-connection-string
      objectName: webhooksdb-connection-string                   
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    keyvaultName: {{ .Values.KEYVAULT.NAME }}
    clientID: {{ .Values.WORKLOAD_ID.CLIENT_ID }}
    cloudName: ""                                                  
    objects:  |
      array:
        - |
          objectName: catalogdb-connection-string
          objectType: secret
          objectVersion: ""         
        - |
          objectName: identitydb-connection-string
          objectType: secret
          objectVersion: ""     
        - |
          objectName: orderingdb-connection-string
          objectType: secret
          objectVersion: ""     
        - |
          objectName: webhooksdb-connection-string
          objectType: secret
          objectVersion: ""                                  
    tenantId: {{ .Values.WORKLOAD_ID.TENANT_ID }}
{{- end }} 
---
{{- if .Values.DEPLOY.REDIS -}}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: eshop-redis-secrets
  namespace: {{ .Values.NAMESPACE }}
spec:
  provider: azure
  secretObjects:
  - secretName: eshop-redis-secrets                   
    type: Opaque                            
    data:                 
    - key:  redis-connection-string
      objectName:  redis-connection-string    
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    keyvaultName: {{ .Values.KEYVAULT.NAME }}
    clientID: {{ .Values.WORKLOAD_ID.CLIENT_ID }}
    cloudName: ""                                                  
    objects:  |
      array:
        - |
          objectName: redis-connection-string
          objectType: secret
          objectVersion: ""                               
    tenantId: {{ .Values.WORKLOAD_ID.TENANT_ID }}
{{- end }}    