APP_NAME                                : ""

OTEL:
  ZIPKIN_ENDPOINT                       : "http://otel-collector.otel-system.svc.cluster.local:9411/api/v2/spans"
  ENDPOINT                              : "http://otel-collector.otel-system.svc.cluster.local:4317"
  VERSION                               : "0.98.0"

APP_INSIGHTS:
  CONNECTION_STRING                     : ""

WEBAPP_DOMAIN                           : ""

CERT:
  EMAIL_ADDRESS                         : ""
  IDENTITY_URL_SERVICE_NAME             : "default_value"
  IDENTITY_URL_CHALLENGE_PATH           : "default_value"
  SHOP_URL_SERVICE_NAME                 : "default_value"
  SHOP_URL_CHALLENGE_PATH               : "default_value"